# Generated by Django 3.1.14 on 2023-07-15 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('descricao', models.CharField(max_length=255)),
                ('valor_transacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_conta', models.CharField(max_length=10, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
