# Generated by Django 3.1.14 on 2023-07-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='tipo',
            field=models.CharField(choices=[('Poupanca', 'Poupança'), ('Corrente', 'Corrente')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
